// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamingService.Data;

#nullable disable

namespace StreamingService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenreVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("VideoId");

                    b.ToTable("genre_videos");
                });

            modelBuilder.Entity("StreamingService.Models.Audiotrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioCodec")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("BitrateKbps")
                        .HasColumnType("int");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("VideoEpisodesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoEpisodesId");

                    b.ToTable("audiotracks");
                });

            modelBuilder.Entity("StreamingService.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VideoId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("StreamingService.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("StreamingService.Models.GenreTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOriginal")
                        .HasColumnType("bit");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("genre_translations");
                });

            modelBuilder.Entity("StreamingService.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("method");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("StreamingService.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("StreamingService.Models.PersonRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("person_roles");
                });

            modelBuilder.Entity("StreamingService.Models.PersonTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsOriginal")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("person_translations");
                });

            modelBuilder.Entity("StreamingService.Models.PersonVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PersonRoleId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonRoleId");

                    b.HasIndex("VideoId");

                    b.ToTable("person_videos");
                });

            modelBuilder.Entity("StreamingService.Models.SubscriptionLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.ToTable("subscription_levels");
                });

            modelBuilder.Entity("StreamingService.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Features")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("features");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("PeriodDays")
                        .HasColumnType("int")
                        .HasColumnName("period_days");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int>("SubscriptionLevelId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_level_id");

                    b.Property<int>("TrialDays")
                        .HasColumnType("int")
                        .HasColumnName("trial_days");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionLevelId");

                    b.ToTable("subscription_plans");
                });

            modelBuilder.Entity("StreamingService.Models.UserCommentLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserProfileId", "CommentId")
                        .IsUnique();

                    b.ToTable("user_comment_like");
                });

            modelBuilder.Entity("StreamingService.Models.UserEpisodesHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFullyWatched")
                        .HasColumnType("bit")
                        .HasColumnName("is_fully_watched");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_watched_at");

                    b.Property<int>("PausedWatchTime")
                        .HasColumnType("int")
                        .HasColumnName("paused_watch_time");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("VideoEpisodeId")
                        .HasColumnType("int")
                        .HasColumnName("video_episodes_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VideoEpisodeId");

                    b.ToTable("user_episodes_history");
                });

            modelBuilder.Entity("StreamingService.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user_profile");
                });

            modelBuilder.Entity("StreamingService.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_renew");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubscriptionEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("subscription_end_date");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_plan_id");

                    b.Property<DateTime>("SubscriptionStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("subscription_start_date");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SubscriptionPlanId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("users_subscriptions");
                });

            modelBuilder.Entity("StreamingService.Models.UserVideoFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserProfileId", "VideoId")
                        .IsUnique();

                    b.ToTable("user_video_favorite");
                });

            modelBuilder.Entity("StreamingService.Models.UserVideoRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("UserProfileId", "VideoId")
                        .IsUnique();

                    b.ToTable("user_video_rating");
                });

            modelBuilder.Entity("StreamingService.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinAccess")
                        .HasColumnType("int");

                    b.Property<long>("RatingCount")
                        .HasColumnType("bigint");

                    b.Property<long>("RatingSum")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MinAccess");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("VideoSeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoSeasonId");

                    b.ToTable("video_episodes");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisodeDailyStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("TotalUserViews")
                        .HasColumnType("int")
                        .HasColumnName("total_user_views");

                    b.Property<int>("VideoEpisodeId")
                        .HasColumnType("int")
                        .HasColumnName("video_episodes_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoEpisodeId");

                    b.ToTable("video_episode_daily_stats");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisodeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool?>("IsOriginal")
                        .HasColumnType("bit");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VideoEpisodesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoEpisodesId");

                    b.ToTable("video_episode_translations");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisodeViewTimedLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("VideoEpisodeId")
                        .HasColumnType("int")
                        .HasColumnName("video_episodes _id ");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VideoEpisodeId");

                    b.ToTable("video_episode_view_timed_log");
                });

            modelBuilder.Entity("StreamingService.Models.VideoFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BitrateKbps")
                        .HasColumnType("int");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("VideoEpisodesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoEpisodesId");

                    b.ToTable("video_files");
                });

            modelBuilder.Entity("StreamingService.Models.VideoImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("video_images");
                });

            modelBuilder.Entity("StreamingService.Models.VideoSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NumberOfSeason")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("video_seasons");
                });

            modelBuilder.Entity("StreamingService.Models.VideoSubtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("VideoEpisodesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoEpisodesId");

                    b.ToTable("video_subtitles");
                });

            modelBuilder.Entity("StreamingService.Models.VideoTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool?>("IsOriginal")
                        .HasColumnType("bit");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("video_translations");
                });

            modelBuilder.Entity("GenreVideo", b =>
                {
                    b.HasOne("StreamingService.Models.Genre", "Genre")
                        .WithMany("GenreVideos")
                        .HasForeignKey("GenreId")
                        .IsRequired();

                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("GenreVideos")
                        .HasForeignKey("VideoId")
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.Audiotrack", b =>
                {
                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisode")
                        .WithMany("Audiotracks")
                        .HasForeignKey("VideoEpisodesId")
                        .IsRequired();

                    b.Navigation("VideoEpisode");
                });

            modelBuilder.Entity("StreamingService.Models.Comment", b =>
                {
                    b.HasOne("StreamingService.Models.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("Comments")
                        .HasForeignKey("VideoId")
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("UserProfile");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.Genre", b =>
                {
                    b.HasOne("StreamingService.Models.Genre", null)
                        .WithMany("Genres")
                        .HasForeignKey("GenreId");
                });

            modelBuilder.Entity("StreamingService.Models.GenreTranslation", b =>
                {
                    b.HasOne("StreamingService.Models.Genre", "Genre")
                        .WithMany("GenreTranslations")
                        .HasForeignKey("GenreId")
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("StreamingService.Models.PersonTranslation", b =>
                {
                    b.HasOne("StreamingService.Models.Person", "Person")
                        .WithMany("PersonTranslations")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StreamingService.Models.PersonVideo", b =>
                {
                    b.HasOne("StreamingService.Models.Person", "Person")
                        .WithMany("PersonsVideos")
                        .HasForeignKey("PersonId")
                        .IsRequired();

                    b.HasOne("StreamingService.Models.PersonRole", "PersonRole")
                        .WithMany("PersonsVideos")
                        .HasForeignKey("PersonRoleId")
                        .IsRequired();

                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("PersonVideos")
                        .HasForeignKey("VideoId")
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("PersonRole");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.SubscriptionPlan", b =>
                {
                    b.HasOne("StreamingService.Models.SubscriptionLevel", "SubscriptionLevel")
                        .WithMany()
                        .HasForeignKey("SubscriptionLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionLevel");
                });

            modelBuilder.Entity("StreamingService.Models.UserCommentLike", b =>
                {
                    b.HasOne("StreamingService.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("StreamingService.Models.UserEpisodesHistory", b =>
                {
                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisode")
                        .WithMany()
                        .HasForeignKey("VideoEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("VideoEpisode");
                });

            modelBuilder.Entity("StreamingService.Models.UserSubscription", b =>
                {
                    b.HasOne("StreamingService.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("StreamingService.Models.UserVideoFavorite", b =>
                {
                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("Favorites")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.UserVideoRating", b =>
                {
                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("Ratings")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.Video", b =>
                {
                    b.HasOne("StreamingService.Models.SubscriptionLevel", "SubscriptionLevel")
                        .WithMany()
                        .HasForeignKey("MinAccess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionLevel");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisode", b =>
                {
                    b.HasOne("StreamingService.Models.VideoSeason", "VideoSeason")
                        .WithMany("Episodes")
                        .HasForeignKey("VideoSeasonId")
                        .IsRequired();

                    b.Navigation("VideoSeason");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisodeDailyStats", b =>
                {
                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisode")
                        .WithMany()
                        .HasForeignKey("VideoEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoEpisode");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisodeTranslation", b =>
                {
                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisode")
                        .WithMany("VideoEpisodeTranslations")
                        .HasForeignKey("VideoEpisodesId")
                        .IsRequired();

                    b.Navigation("VideoEpisode");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisodeViewTimedLog", b =>
                {
                    b.HasOne("StreamingService.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisode")
                        .WithMany()
                        .HasForeignKey("VideoEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("VideoEpisode");
                });

            modelBuilder.Entity("StreamingService.Models.VideoFile", b =>
                {
                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisode")
                        .WithMany("VideoFiles")
                        .HasForeignKey("VideoEpisodesId")
                        .IsRequired();

                    b.Navigation("VideoEpisode");
                });

            modelBuilder.Entity("StreamingService.Models.VideoImage", b =>
                {
                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("Images")
                        .HasForeignKey("VideoId")
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.VideoSeason", b =>
                {
                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("Seasons")
                        .HasForeignKey("VideoId")
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.VideoSubtitle", b =>
                {
                    b.HasOne("StreamingService.Models.VideoEpisode", "VideoEpisodes")
                        .WithMany("VideoSubtitles")
                        .HasForeignKey("VideoEpisodesId")
                        .IsRequired();

                    b.Navigation("VideoEpisodes");
                });

            modelBuilder.Entity("StreamingService.Models.VideoTranslation", b =>
                {
                    b.HasOne("StreamingService.Models.Video", "Video")
                        .WithMany("Translations")
                        .HasForeignKey("VideoId")
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamingService.Models.Genre", b =>
                {
                    b.Navigation("GenreTranslations");

                    b.Navigation("GenreVideos");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("StreamingService.Models.Person", b =>
                {
                    b.Navigation("PersonTranslations");

                    b.Navigation("PersonsVideos");
                });

            modelBuilder.Entity("StreamingService.Models.PersonRole", b =>
                {
                    b.Navigation("PersonsVideos");
                });

            modelBuilder.Entity("StreamingService.Models.Video", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("GenreVideos");

                    b.Navigation("Images");

                    b.Navigation("PersonVideos");

                    b.Navigation("Ratings");

                    b.Navigation("Seasons");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("StreamingService.Models.VideoEpisode", b =>
                {
                    b.Navigation("Audiotracks");

                    b.Navigation("VideoEpisodeTranslations");

                    b.Navigation("VideoFiles");

                    b.Navigation("VideoSubtitles");
                });

            modelBuilder.Entity("StreamingService.Models.VideoSeason", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
