//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamingService.Resources.AuthTexts", typeof(AuthTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще трохи терпіння, і ти всередині! Введи свої дані, натисни “Увійти” — і твої улюблені серіали й фільми вже чекають, як актори на зйомках. Тут без драм із паролями та дивних помилок — тільки ти, плед, попкорн і нескінченний каталог контенту. Якщо введеш пароль не з першого разу — не переживай, ми не знімемо тебе з ролі, просто ще трохи потренуйся перед камерою. І пам’ятай: твоя підписка активна, а серії самі себе не подивляться!.
        /// </summary>
        public static string SignInBackground {
            get {
                return ResourceManager.GetString("SignInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ну знову ці форми заповнювати ім’я прізвище пошта пароль і ніби я в банк заходжу а не кіно дивитись але добре хай буде бо без цього ніяк головне щоб потім не питало кожен раз “ви справді це ви?” я просто хочу включити фільм і забути про все навколо бо іноді єдиний нормальний пароль це плед какао і вечір на дивані і головне щоб не треба було кожен раз перевіряти хто я бо я вже тут і просто хочу насолоджуватись переглядом.
        /// </summary>
        public static string SignupBackground {
            get {
                return ResourceManager.GetString("SignupBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О, знову ця Угода про підписку. Таке враження, ніби я землю в оренду беру, а не просто хочу серіальчик подивитись. Ну, гаразд, заради попкорну і нових епізодів я готовий на все. Тільки б після всіх цих слів-паразитів не вилізла ще одна сторінка з умовами, бо мої очі вже бачать субтитри замість літер. Нехай ця папірецька бюрократія дасть мені нарешті спокій, щоб я міг просто насолоджуватись!.
        /// </summary>
        public static string SubscriberAgreementBackground {
            get {
                return ResourceManager.GetString("SubscriberAgreementBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О ні знову ці тарифи стандарт преміум мега ультра а може просто дайте мені кнопку “дивитись все” і все але ні треба подумати що справді потрібно я ж не плачу за телевізор який не дивлюсь може й тут обрати своє без реклами без нервів без пауз і хай кожен знайде те що йому підходить бо головне не кількість екранів а кайф від перегляду.
        /// </summary>
        public static string SubscriptionBackground {
            get {
                return ResourceManager.GetString("SubscriptionBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О ні це знову воно священне введення картки ніби я таємний агент який розкриває код сейфа а не просто оплачую підписку заради вечірнього відпочинку ну добре хай буде лише б всі цифри співпали і не вискочила помилка 404 мій гаманець не готовий до таких нервів а серіали вже зачекались і нехай цей магічний момент поповнення балансу відкриє мені світ безмежних розваг бо головне не скільки ти заплатив а як багато ти встиг подивитись.
        /// </summary>
        public static string SubscriptionConfirmation_error {
            get {
                return ResourceManager.GetString("SubscriptionConfirmation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О ні це знову воно священне введення картки ніби я таємний агент який розкриває код сейфа а не просто оплачую підписку заради вечірнього відпочинку ну добре хай буде лише б всі цифри співпали і не вискочила помилка 404 мій гаманець не готовий до таких нервів а серіали вже зачекались і нехай цей магічний момент поповнення балансу відкриє мені світ безмежних розваг бо головне не скільки ти заплатив а як багато ти встиг подивитись.
        /// </summary>
        public static string SubscriptionConfirmationBackground {
            get {
                return ResourceManager.GetString("SubscriptionConfirmationBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово! Твоя підписка активна — наче секретний ритуал вводу картки пройшов успішно. Жодної помилки, жодної драми. Тепер можна спокійно відкривати Lumeo й робити вигляд, що подивишся “тільки одну серію”..
        /// </summary>
        public static string SuccessScreenBackground {
            get {
                return ResourceManager.GetString("SuccessScreenBackground", resourceCulture);
            }
        }
    }
}
